 version: '3'
  services:
    node:
      tty: true
      stdin_open: true
      container_name: eslint-config-react-crowdanalyzer
      build:
        context: .
      volumes:
        - .:/var/code:rw
      entrypoint: './startup.sh'
